# This is a basic workflow to help you get started with Actions

name: Mocha CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
  schedule:
    - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Yarn
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      
      - name: Run Yarn Test
        uses: borales/actions-yarn@v3.0.0
        with:
         cmd: run mocha:test
